# ----------------------------------------
# Created on: Sun Sep 21 23:33:02 2025
# Auto generated by Pango
# ----------------------------------------

vlib  work
vmap  work ./work
vmap  usim "D:/modelsim/pango_sim_lib/usim"
vmap  adc_e2 "D:/modelsim/pango_sim_lib/adc_e2"
vmap  ddc_e2 "D:/modelsim/pango_sim_lib/ddc_e2"
vmap  dll_e2 "D:/modelsim/pango_sim_lib/dll_e2"
vmap  hsstlp_lane "D:/modelsim/pango_sim_lib/hsstlp_lane"
vmap  hsstlp_pll "D:/modelsim/pango_sim_lib/hsstlp_pll"
vmap  iolhr_dft "D:/modelsim/pango_sim_lib/iolhr_dft"
vmap  ipal_e1 "D:/modelsim/pango_sim_lib/ipal_e1"
vmap  ipal_e2 "D:/modelsim/pango_sim_lib/ipal_e2"
vmap  iserdes_e2 "D:/modelsim/pango_sim_lib/iserdes_e2"
vmap  oserdes_e2 "D:/modelsim/pango_sim_lib/oserdes_e2"
vmap  pciegen2 "D:/modelsim/pango_sim_lib/pciegen2"
vlog -work work   \
"F:/pds_project/2_2_1sim/2_2_sim/3_2_sim/source/led_test.v" \
"F:/pds_project/2_2_1sim/2_2_sim/3_2_sim/source/signal_analyzer_top.v" \
"F:/pds_project/2_2_1sim/2_2_sim/3_2_sim/source/tb_led_test.v" \
"F:/pds_project/2_2_1sim/2_2_sim/3_2_sim/source/signal_generator_tb.v" 

# ----------------------------------------
